name: one_branch
run-name: ${{github.actor}} is testing your workflow that is executing on one branch
on: [push]
jobs:
  if: github.ref_name == 'demo'
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"