name: Worflow with checkout and run py with multiple version
on:
  push:
jobs:
  run-py-multiples-versions:
    strategy:
      matrix:
        version: [3.8,3.9,3.10]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version }}
      - run: python --version