name: Worflow with docker
on:
  push:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v3
        with:
          push: 'true'
          tags: 'esobieraj/exo4-4:${{github.ref_name}}'