name: Worflow with ggroupes
on:
  push:
jobs:
  log_group:
    runs-on: ubuntu-latest
    steps:
      - name: "ecole-it"
      - run: | 
          echo "::group:: ecole-it"
          echo "::warning:: Bonjour Ecole-it"
          echo "::endgroup::"
